version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:us-east-1:757656574143:task-definition/pyweb:1  
        LoadBalancerInfo:
          ContainerName: "pyweb"
          ContainerPort: 1234
