version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Logging into Amazon ECR..
      - aws ecr get-login-password --region cn-northwest-1 | docker login --username AWS --password-stdin 314451195721.dkr.ecr.cn-northwest-1.amazonaws.com.cn
  build:
    commands:
      - echo build docker image
      - docker build -t web .
      - docker tag web:latest 314451195721.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cicdtest:latest
  post_build:
    commands:
      - echo Build Completed on `date`
      - docker push 314451195721.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cicdtest:latest
      - echo Writing image definitions file...
      - printf '{"ImageURI":"314451195721.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cicdtest:latest"}' > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - taskdef.json
    - appspec.yaml
